name: cli-ci

on:
  pull_request:
    paths:
      - "cli/**"
      - ".github/workflows/cli-ci.yml"
      - "go.mod"
    branches: [main, feature/sjad]

permissions:
  contents: read
  pull-requests: write

jobs:
  azd-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.23.0"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.1
          args: -v --timeout 10m0s
          working-directory: cli/azd

  cspell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g cspell@8.13.1
      - name: Spell check for go and docs
        run: cspell lint '**/*.{go,md}' --config ./cli/azd/.vscode/cspell.yaml --root ./cli/azd --no-progress

  bicep-lint:
    uses: ./.github/workflows/lint-bicep.yml
