# NOTE: currently azure-sdk-actions only hosts check enforcer code.
# If further functionality is added, this name should be updated to reflect
# the more generic behavior
name: Check Enforcer

on:
  check_suite:
    types: [completed]
  issue_comment:
    types: [created]
  # Trigger off other github actions, because otherwise a check_suite completed event consisting
  # entirely of github actions won't trigger this action.
  workflow_run:
    types: [completed]
    workflows: ["cli-ci"]

permissions: {}

jobs:
  event-handler:
    permissions:
      statuses: write # to set status (azure/azure-sdk-actions)
      pull-requests: write # to read pull requests and write comments (azure/azure-sdk-actions)
      checks: read # to read check status (azure/azure-sdk-actions)
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    runs-on: ubuntu-latest
    steps:
      - uses: azure/azure-sdk-actions@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
