on:
  workflow_call:
  pull_request:
    branches: 
      - main
    paths:
      - eng/scripts/Test-BicepLint.ps1
      - .github/workflows/lint-bicep.yml
    


jobs:
  bicep-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade bicep
        run: |
          which bicep
          sudo curl -o $(which bicep) -L https://github.com/Azure/bicep/releases/download/v0.39.26/bicep-linux-x64
          sudo chmod +x $(which bicep)
      - name: Lint .bicep files
        run: $ErrorActionPreference='Continue'; eng/scripts/Test-BicepLint.ps1 -Verbose
        shell: pwsh
