name: shellcheck

on:
  pull_request:
    paths:
      - "**.sh"
      - ".github/workflows/shellcheck.yml"
      - ".github/shellcheck-matcher.json"
    branches: [main]

# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed shell scripts
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_SH_FILES=$(git diff --name-only --diff-filter=ACMRT origin/${{ github.base_ref }}...HEAD | grep '\.sh$' || true)
          if [ -z "$CHANGED_SH_FILES" ]; then
            echo "No shell scripts changed"
            echo "files=" >> $GITHUB_OUTPUT
          else
            echo "Changed shell scripts:"
            echo "$CHANGED_SH_FILES"
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_SH_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      - name: Register ShellCheck problem matcher
        if: steps.changed-files.outputs.files != ''
        run: echo "::add-matcher::.github/shellcheck-matcher.json"
      - name: Run ShellCheck
        if: steps.changed-files.outputs.files != ''
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | xargs shellcheck -f gcc
      - name: Unregister ShellCheck problem matcher
        if: always() && steps.changed-files.outputs.files != ''
        run: echo "::remove-matcher owner=shellcheck-gcc::"
